---
abstract: 'framework to automate HTML forms'
author:
  - 'Max Maischein <corion@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WWW-Mechanize-FormFiller
no_index:
  directory:
    - t
    - inc
requires:
  Data::Random: 0.05
  HTML::Form: 0
  Test::More: 0
version: 0.11
