--- #YAML:1.0
name:                WWW-Mechanize-FormFiller
version:             0.08
abstract:            framework to automate HTML forms
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36_01
distribution_type:   module
requires:     
    Data::Random:                  0.05
    HTML::Form:                    
    Test::More:                    
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Max Maischein <corion@cpan.org>
